name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Install wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1

      - name: Build
        run: cargo build --target wasm32-wasip1

      - name: Run
        shell: bash
        run: wasmtime run --dir=$PWD::/ ./target/wasm32-wasip1/debug/wasm-current-dir-repro.wasm
